package com.jwei.xzfit.ui.device.weather.bean

import kotlinx.serialization.Serializable

@Serializable
data class SearchCityEntity(
    var country: String = "",
    var lat: Double = 0.0,
    var local_names: LocalNameItem = LocalNameItem(),
    var lon: Double = 0.0,
    var name: String = "",
    var state: String = ""
)

@Serializable
data class LocalNameItem(
    var af: String = "",
    var am: String = "",
    var an: String = "",
    var ar: String = "",
    var be: String = "",
    var bg: String = "",
    var bn: String = "",
    var bo: String = "",
    var br: String = "",
    var bs: String = "",
    var ca: String = "",
    var co: String = "",
    var cs: String = "",
    var cy: String = "",
    var da: String = "",
    var de: String = "",
    var dv: String = "",
    var el: String = "",
    var en: String = "",
    var eo: String = "",
    var es: String = "",
    var et: String = "",
    var eu: String = "",
    var fa: String = "",
    var fi: String = "",
    var fr: String = "",
    var fy: String = "",
    var ga: String = "",
    var gd: String = "",
    var gl: String = "",
    var gv: String = "",
    var he: String = "",
    var hi: String = "",
    var hr: String = "",
    var ht: String = "",
    var hu: String = "",
    var hy: String = "",
    var ia: String = "",
    var id: String = "",
    var io: String = "",
    var `is`: String = "",
    var `it`: String = "",
    var ja: String = "",
    var jv: String = "",
    var ka: String = "",
    var kk: String = "",
    var kl: String = "",
    var kn: String = "",
    var ko: String = "",
    var ks: String = "",
    var ku: String = "",
    var la: String = "",
    var lb: String = "",
    var lt: String = "",
    var lv: String = "",
    var mg: String = "",
    var mi: String = "",
    var mk: String = "",
    var ml: String = "",
    var mn: String = "",
    var mr: String = "",
    var ms: String = "",
    var my: String = "",
    var ne: String = "",
    var nl: String = "",
    var nn: String = "",
    var no: String = "",
    var oc: String = "",
    var os: String = "",
    var pa: String = "",
    var pl: String = "",
    var pt: String = "",
    var qu: String = "",
    var ro: String = "",
    var ru: String = "",
    var sa: String = "",
    var si: String = "",
    var sk: String = "",
    var sl: String = "",
    var so: String = "",
    var sq: String = "",
    var sr: String = "",
    var sv: String = "",
    var sw: String = "",
    var ta: String = "",
    var te: String = "",
    var tg: String = "",
    var th: String = "",
    var tl: String = "",
    var tr: String = "",
    var ug: String = "",
    var uk: String = "",
    var ur: String = "",
    var vi: String = "",
    var yi: String = "",
    var yo: String = "",
    var zh: String = ""
)